name: make_gh_pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  make_storybook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: brianzinn

      - name: Set Swap Space
        if: runner.os == 'Linux'
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 4

      - name: install build react-babylon
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          npm install -g yarn
          yarn install
          yarn build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: packages/static/public