name: make_release

on:
  workflow_dispatch:
# push:
#    branches: [ master ]
  
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: install-build
        run: |
          yarn install
          yarn build

      - name: publish
        run: npm publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
