name: make_release

on:
  workflow_dispatch:
    inputs:
      npmVersion:
        description: 'NPM Version (<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease | ...)'
        required: true
        default: 'patch'
      comment:
        description: 'Added to end of commit message and annotated git tag'
        required: true
        default: ' ()'
# push:
#    branches: [ master ]
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.13.2'
          registry-url: 'https://registry.npmjs.org'
          scope: brianzinn

      - name: Configure git
        run: |
          git config user.email "github@wakeskate.com"
          git config user.name "Brian Zinn"
      - name: install workspace
        run: |
          npm install --legacy-peer-deps
      - name: build test coverage
        working-directory: ./packages/react-babylonjs
        run: |
          npm run build
          npm run test:coverage
      - name: version-changelog-commit
        working-directory: ./packages/react-babylonjs
        run: |
          npm version ${{ github.event.inputs.npmVersion }} -m "release %s :package:${{ github.event.inputs.comment }}" --git-tag-version
          git push --follow-tags
          PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          sleep 1m
          ../../node_modules/.bin/gren release --tags=v${PACKAGE_VERSION}
        env:
          GREN_GITHUB_TOKEN: ${{ secrets.GREN_GITHUB_TOKEN }}
      - name: publish npm
        working-directory: ./packages/react-babylonjs
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: publish to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
          path-to-lcov: ./packages/react-babylonjs/coverage/lcov.info
